/** @type {import('tailwindcss').Config} */
export default {
    theme: {
      extend: {
        colors: {
          "surface-container": "#eeedf3",
          "inverse-surface": "#2f3034",
          "on-primary": "#ffffff",
          "primary-fixed": "#e2e2e2",
          "secondary-fixed-dim": "#c6c6c8",
          "on-tertiary": "#ffffff",
          "tertiary": "#5d5f5f",
          "surface-bright": "#faf8fe",
          "on-background": "#1a1b1f",
          "surface-dim": "#dad9df",
          "surface-variant": "#e3e2e7",
          "inverse-on-surface": "#f1f0f5",
          "secondary-fixed": "#e2e2e4",
          "on-tertiary-fixed": "#1a1c1c",
          "on-primary-fixed": "#1a1c1c",
          "error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#454747",
          "on-error": "#ffffff",
          "on-secondary-fixed-variant": "#454749",
          "secondary": "#5d5e60",
          "outline": "#747878",
          "inverse-primary": "#c6c6c7",
          "on-surface": "#1a1b1f",
          "on-primary-container": "#747676",
          "on-surface-variant": "#444748",
          "tertiary-fixed-dim": "#c6c6c7",
          "surface": "#faf8fe",
          "primary-fixed-dim": "#c6c6c7",
          "outline-variant": "#c4c7c8",
          "secondary-container": "#dfdfe1",
          "primary-container": "#ffffff",
          "error": "#ba1a1a",
          "on-secondary-fixed": "#1a1c1d",
          "on-error-container": "#93000a",
          "tertiary-fixed": "#e2e2e2",
          "surface-container-lowest": "#ffffff",
          "tertiary-container": "#ffffff",
          "on-primary-fixed-variant": "#454747",
          "surface-container-low": "#f4f3f8",
          "surface-container-high": "#e9e7ed",
          "on-secondary": "#ffffff",
          "primary": "#5d5f5f",
          "on-tertiary-container": "#747676",
          "on-secondary-container": "#616365",
          "surface-tint": "#5d5f5f",
          "surface-container-highest": "#e3e2e7",
          "background": "#faf8fe"
        },
        fontFamily: {
          'hanken': ['Hanken Grotesk', 'sans-serif']
        }
      },
    },
  }